spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: postgres
    password: 1q2w3e4r
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: devops