spring:
  datasource:
    url: jdbc:mysql://mysql:3306/boards?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: devops